const additionalWords = [
    { russian: "Можете ли вы помочь мне?", english: "Can you help me?" },
    { russian: "Как вас зовут?", english: "What is your name?" },
    { russian: "Меня зовут...", english: "My name is..." },
    { russian: "Откуда вы?", english: "Where are you from?" },
    { russian: "Я из...", english: "I am from..." },
    { russian: "Сколько вам лет?", english: "How old are you?" },
    { russian: "Мне ... лет", english: "I am ... years old" },
    { russian: "Вы говорите по-английски?", english: "Do you speak English?" },
    { russian: "Я не понимаю", english: "I don't understand" },
    { russian: "Повторите, пожалуйста", english: "Please repeat" },
    { russian: "Говорите медленнее, пожалуйста", english: "Please speak slower" },
    { russian: "Я учу русский язык", english: "I am learning Russian" },
    { russian: "Как это сказать по-русски?", english: "How do you say this in Russian?" },
    { russian: "Сколько это стоит?", english: "How much does this cost?" },
    { russian: "Где находится ближайший банкомат?", english: "Where is the nearest ATM?" },
    { russian: "Какой сегодня день?", english: "What day is it today?" },
    { russian: "Сколько времени?", english: "What time is it?" },
    { russian: "Вы можете порекомендовать ресторан?", english: "Can you recommend a restaurant?" },
    { russian: "Где я могу найти аптеку?", english: "Where can I find a pharmacy?" },
    { russian: "Мне нужна помощь", english: "I need help" },
    { russian: "Вызовите скорую помощь", english: "Call an ambulance" },
    { russian: "Где ближайшая больница?", english: "Where is the nearest hospital?" },
    { russian: "У меня болит голова", english: "I have a headache" },
    { russian: "Я потерял свои документы", english: "I lost my documents" },
    { russian: "Где находится посольство?", english: "Where is the embassy?" },
    { russian: "Как добраться до аэропорта?", english: "How do I get to the airport?" },
    { russian: "Какое у вас расписание?", english: "What is your schedule?" },
    { russian: "Когда вы открыты?", english: "When are you open?" },
    { russian: "Могу ли я забронировать столик?", english: "Can I book a table?" },
    { russian: "Как вас зовут?", english: "What is your name?" },
    { russian: "Где находится ближайший отель?", english: "Where is the nearest hotel?" },
    { russian: "У вас есть номер на двоих?", english: "Do you have a room for two?" },
    { russian: "Могу я заплатить картой?", english: "Can I pay by card?" },
    { russian: "Где я могу поменять деньги?", english: "Where can I exchange money?" },
    { russian: "Какая у вас профессия?", english: "What is your profession?" },
    { russian: "Я работаю программистом", english: "I work as a programmer" },
    { russian: "Могу я взять напрокат машину?", english: "Can I rent a car?" },
    { russian: "Как добраться до центра города?", english: "How do I get to the city center?" },
    { russian: "Где находится автобусная остановка?", english: "Where is the bus stop?" },
    { russian: "Какое у вас хобби?", english: "What are your hobbies?" },
    { russian: "Мне нравится читать книги", english: "I like reading books" },
    { russian: "Где я могу найти супермаркет?", english: "Where can I find a supermarket?" },
    { russian: "Сколько стоит этот билет?", english: "How much is this ticket?" },
    { russian: "Вы принимаете наличные?", english: "Do you accept cash?" },
    { russian: "Какие у вас часы работы?", english: "What are your business hours?" },
    { russian: "Где я могу припарковаться?", english: "Where can I park?" },
    { russian: "Как называется эта улица?", english: "What is the name of this street?" },
    { russian: "Где находится ближайшая заправка?", english: "Where is the nearest gas station?" },
    { russian: "Могу я взять это напрокат?", english: "Can I rent this?" }
];

if (typeof words !== 'undefined' && Array.isArray(words)) {
    words.push(...additionalWords);
}
